"""Domain models for the Briefing System."""
from dataclasses import dataclass, field
from typing import List


@dataclass
class UserPreferences:
    """Represents a user's briefing preferences collected via Discord."""
    discord_channel_id: str
    email_address: str
    topics: List[str] = field(default_factory=list)
    keywords: List[str] = field(default_factory=list)
    max_news_per_topic: int = 5


@dataclass
class NewsArticle:
    """Represents a raw news article fetched from the web."""
    title: str
    url: str
    summary: str
    source: str


@dataclass
class Briefing:
    """Represents the final consolidated briefing generated by the AI."""
    user_email: str
    discord_channel_id: str
    content_markdown: str