"""Manual validation script for email sender with real SMTP."""
import os
import sys
from dotenv import load_dotenv

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.services.email_sender import SMTPEmailSender


def main() -> None:
    """Validate email sender with real SMTP connection."""
    load_dotenv()

    smtp_server = os.getenv("SMTP_SERVER")
    smtp_port = os.getenv("SMTP_PORT")
    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")
    sender_email = os.getenv("SENDER_EMAIL")

    if not all([smtp_server, smtp_port, smtp_user, smtp_password, sender_email]):
        print("❌ ERROR: Missing SMTP configuration in .env")
        print("Please set: SMTP_SERVER, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SENDER_EMAIL")
        sys.exit(1)

    print("🔄 Initializing SMTPEmailSender...")
    sender = SMTPEmailSender(
        smtp_server=smtp_server,
        smtp_port=int(smtp_port),
        username=smtp_user,
        password=smtp_password,
        sender_email=sender_email,
    )

    recipient = input("📧 Enter recipient email address: ").strip()
    if not recipient:
        print("❌ ERROR: No recipient email provided")
        sys.exit(1)

    briefing_content = """# Your BrifAI Daily Briefing

## Top Stories

### 1. Story Title One
**Source:** News Agency
Summary of the first story with important details and context about the topic.

### 2. Story Title Two
**Source:** Another News Source
Summary of the second story highlighting key developments in the area.

## Key Takeaways
- Important point 1
- Important point 2
- Important point 3

---
*Generated by BrifAI on 2026-05-10*
"""

    print(f"📡 Sending test briefing to {recipient}...")
    result = sender.send_briefing(recipient, briefing_content)

    if result:
        print("✅ Email sent successfully!")
        print(f"   From: {sender_email}")
        print(f"   To: {recipient}")
        print(f"   Subject: Your BrifAI Daily Briefing")
    else:
        print("❌ Failed to send email (check logs and SMTP configuration)")
        print("\nTroubleshooting:")
        print("- Gmail: Use 'App Password' (not regular password)")
        print("- Check firewall/network blocking port 587")
        print("- Verify SMTP credentials are correct")


if __name__ == "__main__":
    main()
