"""Manual validation script for email sender with real SMTP."""
import os
import sys
from dotenv import load_dotenv

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.delivery.smtp_email_service import SmtpEmailService


def main() -> None:
    """Validate the current SMTP delivery implementation with real SMTP."""
    load_dotenv()

    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = os.getenv("SMTP_PORT")
    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")

    if not all([smtp_host, smtp_port, smtp_user, smtp_password]):
        print("❌ ERROR: Missing SMTP configuration in .env")
        print("Please set: SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD")
        sys.exit(1)

    print("🔄 Initializing SmtpEmailService...")
    service = SmtpEmailService()
    service._host = smtp_host
    service._port = int(smtp_port)
    service._user = smtp_user
    service._password = smtp_password

    recipient = input("📧 Enter recipient email address: ").strip()
    if not recipient:
        print("❌ ERROR: No recipient email provided")
        sys.exit(1)

    briefing_content = """# Your BrifAI Daily Briefing

## Top Stories

### 1. Story Title One
**Source:** News Agency
Summary of the first story with important details and context about the topic.

### 2. Story Title Two
**Source:** Another News Source
Summary of the second story highlighting key developments in the area.

## Key Takeaways
- Important point 1
- Important point 2
- Important point 3

---
*Generated by BrifAI on 2026-05-10*
"""

    print(f"📡 Sending test briefing to {recipient}...")
    result = service.send_briefing(recipient, briefing_content)

    if result:
        print("✅ Email sent successfully!")
        print(f"   From: {smtp_user}")
        print(f"   To: {recipient}")
        print(f"   Subject: Your Daily Briefing")
    else:
        print("❌ Failed to send email (check logs and SMTP configuration)")
        print("\nTroubleshooting:")
        print("- Gmail: Use 'App Password' (not regular password)")
        print("- Check firewall/network blocking port 587")
        print("- Verify SMTP credentials are correct")


if __name__ == "__main__":
    main()
